## -*- encoding: utf-8 -*-
## This file (embed_test_2.sagetex.sage) was *autogenerated* from embed_test_2.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('embed_test_2', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.useimagemagick = True
_st_.blockbegin()
try:
     var('x')
     Z = IntegerRing();
     m = (Z.random_element()/(x+Z.random_element())) + (Z.random_element()/(x+Z.random_element()))
     simplified = m.full_simplify()
except:
 _st_.goboom(15)
_st_.blockend()
try:
 _st_.inline(0, latex(m))
except:
 _st_.goboom(17)
try:
 _st_.inline(1, latex(simplified))
except:
 _st_.goboom(17)
_st_.blockbegin()
try:
     f = (2/(x-3)) - (3/(x+5))
     simp2 = f.full_simplify()
except:
 _st_.goboom(22)
_st_.blockend()
try:
 _st_.inline(2, latex(f))
except:
 _st_.goboom(24)
try:
 _st_.inline(3, latex(simp2))
except:
 _st_.goboom(24)
_st_.endofdoc()
