## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file embed_test_2.sagetex.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_17 = Integer(17); _sage_const_15 = Integer(15); _sage_const_22 = Integer(22); _sage_const_24 = Integer(24)## This file (embed_test_2.sagetex.sage) was *autogenerated* from embed_test_2.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('embed_test_2', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.useimagemagick = True
_st_.blockbegin()
try:
     var('x')
     Z = IntegerRing();
     m = (Z.random_element()/(x+Z.random_element())) + (Z.random_element()/(x+Z.random_element()))
     simplified = m.full_simplify()
except:
 _st_.goboom(_sage_const_15 )
_st_.blockend()
try:
 _st_.inline(_sage_const_0 , latex(m))
except:
 _st_.goboom(_sage_const_17 )
try:
 _st_.inline(_sage_const_1 , latex(simplified))
except:
 _st_.goboom(_sage_const_17 )
_st_.blockbegin()
try:
     f = (_sage_const_2 /(x-_sage_const_3 )) - (_sage_const_3 /(x+_sage_const_5 ))
     simp2 = f.full_simplify()
except:
 _st_.goboom(_sage_const_22 )
_st_.blockend()
try:
 _st_.inline(_sage_const_2 , latex(f))
except:
 _st_.goboom(_sage_const_24 )
try:
 _st_.inline(_sage_const_3 , latex(simp2))
except:
 _st_.goboom(_sage_const_24 )
_st_.endofdoc()
