## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file embed_test.sagetex.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_28 = Integer(28); _sage_const_20 = Integer(20); _sage_const_24 = Integer(24); _sage_const_89 = Integer(89); _sage_const_46 = Integer(46); _sage_const_1269 = Integer(1269); _sage_const_87 = Integer(87); _sage_const_0p2 = RealNumber('0.2'); _sage_const_37 = Integer(37); _sage_const_6p20 = RealNumber('6.20'); _sage_const_39 = Integer(39); _sage_const_16 = Integer(16); _sage_const_59 = Integer(59); _sage_const_14 = Integer(14); _sage_const_57 = Integer(57); _sage_const_35 = Integer(35); _sage_const_52 = Integer(52); _sage_const_51 = Integer(51); _sage_const_158760 = Integer(158760)## This file (embed_test.sagetex.sage) was *autogenerated* from embed_test.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('embed_test', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.useimagemagick = True
_st_.blockbegin()
try:
     var('x')
     m = (_sage_const_1 /(x-_sage_const_2 )) + (_sage_const_1 /(x+_sage_const_2 ))
     simplified = m.full_simplify()
except:
 _st_.goboom(_sage_const_14 )
_st_.blockend()
try:
 _st_.inline(_sage_const_0 , latex(m))
except:
 _st_.goboom(_sage_const_16 )
try:
 _st_.inline(_sage_const_1 , latex(simplified))
except:
 _st_.goboom(_sage_const_20 )
try:
 _st_.inline(_sage_const_2 , latex(number_of_partitions(_sage_const_1269 )))
except:
 _st_.goboom(_sage_const_24 )
try:
 _st_.inline(_sage_const_3 , latex(factor(_sage_const_158760 )))
except:
 _st_.goboom(_sage_const_28 )
_st_.blockbegin()
try:
     __tmp__=var("x"); g = symbolic_expression(x**_sage_const_6 -_sage_const_3 *x**_sage_const_2 +_sage_const_3 *x-_sage_const_4 ).function(x);
     __tmp__=var("x"); h = symbolic_expression((_sage_const_2 *x - _sage_const_4 )**_sage_const_6 ).function(x);
except:
 _st_.goboom(_sage_const_35 )
_st_.blockend()
try:
 _st_.inline(_sage_const_4 , latex(g(x)))
except:
 _st_.goboom(_sage_const_37 )
try:
 _st_.inline(_sage_const_5 , latex(factor(g(x))))
except:
 _st_.goboom(_sage_const_37 )
try:
 _st_.inline(_sage_const_6 , latex(expand((_sage_const_2 *x - _sage_const_4 )**_sage_const_6 )))
except:
 _st_.goboom(_sage_const_39 )
_st_.blockbegin()
try:
     __tmp__=var("x"); f = symbolic_expression(exp(x) * sin(_sage_const_2 *x)).function(x)
except:
 _st_.goboom(_sage_const_46 )
_st_.blockend()
try:
 _st_.inline(_sage_const_7 , latex(f(x)))
except:
 _st_.goboom(_sage_const_51 )
try:
 _st_.inline(_sage_const_8 , latex(diff(f, x, _sage_const_2 )(x)))
except:
 _st_.goboom(_sage_const_52 )
try:
 _st_.plot(_sage_const_0 , format='notprovided', _p_=plot(f, -_sage_const_2 , _sage_const_2 , title=r'$f(x)$', figsize=_sage_const_3 ))
except:
 _st_.goboom(_sage_const_57 )
try:
 _st_.plot(_sage_const_1 , format='notprovided', _p_=polar_plot([_sage_const_2 +_sage_const_3 *sin(x)], (x, _sage_const_0 , _sage_const_2 *pi),color='black', figsize=[_sage_const_3 ,_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_59 )
_st_.blockbegin()
try:
     x = var('x')
     y = var('y')
     step = _sage_const_0p2 
     x1 = -_sage_const_3 
     x2 = _sage_const_3 
     y1 = -_sage_const_3 
     y2 = _sage_const_6p20 
 
     output1 = ""
     output1 += r"\begin{tikzpicture}[scale=1.0]"
     output1 += r"\begin{axis}[xlabel=$x$,ylabel=$y$,zlabel=$z$,view={25}{30},xmin=%d, xmax=%d, ymin=%d, ymax=%d]"%(x1,x2,y1,y2-step)
     output1 += r"\addplot3[surf,mesh/rows=%d,opacity=0.75] coordinates {"%((y2-step-y1)/step+_sage_const_1 )
     for y in srange(y1,y2,step):
         for x in srange(x1,x2,step):
             #output += ""
             output1 += r"(%f, %f, %f) "%(x,y,sin(x)*sin(y))
 
     output1 += r"};"
     output1 += r"\end{axis}"
     output1 += r"\end{tikzpicture}"
except:
 _st_.goboom(_sage_const_87 )
_st_.blockend()
try:
 _st_.inline(_sage_const_9 , output1)
except:
 _st_.goboom(_sage_const_89 )
_st_.endofdoc()
