## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file embed_test.sagetex.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_8 = Integer(8); _sage_const_200 = Integer(200); _sage_const_22 = Integer(22); _sage_const_26 = Integer(26); _sage_const_55 = Integer(55); _sage_const_44 = Integer(44); _sage_const_1269 = Integer(1269); _sage_const_49 = Integer(49); _sage_const_1p5 = RealNumber('1.5'); _sage_const_68 = Integer(68); _sage_const_0p8 = RealNumber('0.8'); _sage_const_12 = Integer(12); _sage_const_14 = Integer(14); _sage_const_33 = Integer(33); _sage_const_18 = Integer(18); _sage_const_35 = Integer(35); _sage_const_37 = Integer(37); _sage_const_50 = Integer(50); _sage_const_72 = Integer(72); _sage_const_158760 = Integer(158760)## This file (embed_test.sagetex.sage) was *autogenerated* from embed_test.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('embed_test', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.useimagemagick = True
_st_.blockbegin()
try:
     var('x')
     m = (_sage_const_1 /(x-_sage_const_2 )) + (_sage_const_1 /(x+_sage_const_2 ))
     simplified = m.full_simplify()
except:
 _st_.goboom(_sage_const_12 )
_st_.blockend()
try:
 _st_.inline(_sage_const_0 , latex(m))
except:
 _st_.goboom(_sage_const_14 )
try:
 _st_.inline(_sage_const_1 , latex(simplified))
except:
 _st_.goboom(_sage_const_18 )
try:
 _st_.inline(_sage_const_2 , latex(number_of_partitions(_sage_const_1269 )))
except:
 _st_.goboom(_sage_const_22 )
try:
 _st_.inline(_sage_const_3 , latex(factor(_sage_const_158760 )))
except:
 _st_.goboom(_sage_const_26 )
_st_.blockbegin()
try:
     __tmp__=var("x"); g = symbolic_expression(x**_sage_const_6 -_sage_const_3 *x**_sage_const_2 +_sage_const_3 *x-_sage_const_4 ).function(x);
     __tmp__=var("x"); h = symbolic_expression((_sage_const_2 *x - _sage_const_4 )**_sage_const_6 ).function(x);
except:
 _st_.goboom(_sage_const_33 )
_st_.blockend()
try:
 _st_.inline(_sage_const_4 , latex(g(x)))
except:
 _st_.goboom(_sage_const_35 )
try:
 _st_.inline(_sage_const_5 , latex(factor(g(x))))
except:
 _st_.goboom(_sage_const_35 )
try:
 _st_.inline(_sage_const_6 , latex(expand((_sage_const_2 *x - _sage_const_4 )**_sage_const_6 )))
except:
 _st_.goboom(_sage_const_37 )
_st_.blockbegin()
try:
     __tmp__=var("x"); f = symbolic_expression(exp(x) * sin(_sage_const_2 *x)).function(x)
except:
 _st_.goboom(_sage_const_44 )
_st_.blockend()
try:
 _st_.inline(_sage_const_7 , latex(f(x)))
except:
 _st_.goboom(_sage_const_49 )
try:
 _st_.inline(_sage_const_8 , latex(diff(f, x, _sage_const_2 )(x)))
except:
 _st_.goboom(_sage_const_50 )
try:
 _st_.plot(_sage_const_0 , format='notprovided', _p_=plot(f, -_sage_const_2 , _sage_const_2 , figsize=_sage_const_3 ))
except:
 _st_.goboom(_sage_const_55 )
_st_.blockbegin()
try:
     u,v = var("u,v")
     G = parametric_plot3d([cos(u)*v, sin(u)*v, _sage_const_3 /_sage_const_2 -_sage_const_3 *v/_sage_const_2 ], (u, _sage_const_0 , _sage_const_2 *pi), (v, _sage_const_0 , _sage_const_1p5 ), opacity = _sage_const_0p8 , plot_points=[_sage_const_200 ,_sage_const_200 ]) # the cone
  # G = graphs.CubeGraph(5)
except:
 _st_.goboom(_sage_const_68 )
_st_.blockend()
try:
 _st_.plot(_sage_const_1 , format='png', _p_=G.plot3d(engine='tachyon'))
except:
 _st_.goboom(_sage_const_72 )
_st_.endofdoc()
