## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file precal_partial_fraction_ws.sagetex.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_200 = Integer(200); _sage_const_22 = Integer(22); _sage_const_26 = Integer(26); _sage_const_24 = Integer(24); _sage_const_44 = Integer(44); _sage_const_61 = Integer(61); _sage_const_1269 = Integer(1269); _sage_const_1p5 = RealNumber('1.5'); _sage_const_0p8 = RealNumber('0.8'); _sage_const_39 = Integer(39); _sage_const_38 = Integer(38); _sage_const_11 = Integer(11); _sage_const_15 = Integer(15); _sage_const_57 = Integer(57); _sage_const_33 = Integer(33); _sage_const_158760 = Integer(158760)## This file (precal_partial_fraction_ws.sagetex.sage) was *autogenerated* from precal_partial_fraction_ws.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('precal_partial_fraction_ws', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.useimagemagick = True
try:
 _st_.inline(_sage_const_0 , latex(number_of_partitions(_sage_const_1269 )))
except:
 _st_.goboom(_sage_const_11 )
try:
 _st_.inline(_sage_const_1 , latex(factor(_sage_const_158760 )))
except:
 _st_.goboom(_sage_const_15 )
_st_.blockbegin()
try:
     __tmp__=var("x"); g = symbolic_expression(x**_sage_const_6 -_sage_const_3 *x**_sage_const_2 +_sage_const_3 *x-_sage_const_4 ).function(x);
     __tmp__=var("x"); h = symbolic_expression((_sage_const_2 *x - _sage_const_4 )**_sage_const_6 ).function(x);
except:
 _st_.goboom(_sage_const_22 )
_st_.blockend()
try:
 _st_.inline(_sage_const_2 , latex(g(x)))
except:
 _st_.goboom(_sage_const_24 )
try:
 _st_.inline(_sage_const_3 , latex(factor(g(x))))
except:
 _st_.goboom(_sage_const_24 )
try:
 _st_.inline(_sage_const_4 , latex(expand((_sage_const_2 *x - _sage_const_4 )**_sage_const_6 )))
except:
 _st_.goboom(_sage_const_26 )
_st_.blockbegin()
try:
     __tmp__=var("x"); f = symbolic_expression(exp(x) * sin(_sage_const_2 *x)).function(x)
except:
 _st_.goboom(_sage_const_33 )
_st_.blockend()
try:
 _st_.inline(_sage_const_5 , latex(f(x)))
except:
 _st_.goboom(_sage_const_38 )
try:
 _st_.inline(_sage_const_6 , latex(diff(f, x, _sage_const_2 )(x)))
except:
 _st_.goboom(_sage_const_39 )
try:
 _st_.plot(_sage_const_0 , format='notprovided', _p_=plot(f, -_sage_const_2 , _sage_const_2 , figsize=_sage_const_3 ))
except:
 _st_.goboom(_sage_const_44 )
_st_.blockbegin()
try:
     u,v = var("u,v")
     G = parametric_plot3d([cos(u)*v, sin(u)*v, _sage_const_3 /_sage_const_2 -_sage_const_3 *v/_sage_const_2 ], (u, _sage_const_0 , _sage_const_2 *pi), (v, _sage_const_0 , _sage_const_1p5 ), opacity = _sage_const_0p8 , plot_points=[_sage_const_200 ,_sage_const_200 ]) # the cone
  # G = graphs.CubeGraph(5)
except:
 _st_.goboom(_sage_const_57 )
_st_.blockend()
try:
 _st_.plot(_sage_const_1 , format='png', _p_=G.plot3d(engine='tachyon'))
except:
 _st_.goboom(_sage_const_61 )
_st_.endofdoc()
