
︠076d32b0-37d7-41ef-becf-0bb406ce79e2i︠
%md
# Simple Animations
========================
## A SAGE worksheet documenting how basic animations work in sage cloud math
︡32ad24a2-83bd-4f43-92c1-ca814f8383d1︡{"html":"<h1># Simple Animations</h1>\n\n<h2>A SAGE worksheet documenting how basic animations work in sage cloud math</h2>\n"}︡
︠b11890e5-bb31-4f0f-a5d8-f89dbb45957br︠

# start simply by graphing a point
var('x y')
︡75b1c513-8e94-4d95-8775b1c513-8e94-4d95-8785-0565c8513d32︡
︠3a51aab6-820f-43dc-bfae-f3d5a36f3156︠
x=2;y=4;
point1 = point((x,y))
︡c2c880ca-ad41-413a-bbb4-b2d59199b73c︡
︠6d7dfa8b-851a-4245-b271-d099f4e5b422︠
plot(point1)
︡2f8bd8c9-2c29-4ae3-ae7b-4632081b2780︡{"once":false,"file":{"show":true,"uuid":"8d7e71cd-c58b-49ea-babc-ca8f59a66ea0","filename":"/projects/71d05d9f-884f-4ae9-80d7-2563cc75a382/.sage/temp/compute6dc2/24274/tmp_WHJomx.png"}}︡
︠ff4af155-95e2-494a-a183-ebd6d435dfaf︠
points = [point((i,3)) for i in srange(0,4,1)]
plot(points)
︡b49a2ae6-9c72-4670-90c6-a6e441794e8f︡{"once":false,"file":{"show":true,"uuid":"3ea23012-3bae-4551-987a-f65bdae4fab1","filename":"/projects/71d05d9f-884f-4ae9-80d7-2563cc75a382/.sage/temp/compute6dc2/24274/tmp_j9xQzx.png"}}︡
︠3aa11c98-8cd5-4224-bf44-300a59a09ac9︠
# the animate function takes the following arguments:
# * the first is a reference to a graphics object. here it is a point a list of points generated by the [ ... ] syntax
# * the rest of the arguments set up the window size for the plot
# which is displayed using the show() command.
a = animate([point((i,3)) for i in srange(0,4,.1)],xmin=0,ymin=0,xmax=5,ymax=4)
a.show() # optional -- ImageMagick
︡0d9c0574-6a7e-44f9-9bde-5bb31cbc9420︡{"once":false,"file":{"show":true,"uuid":"2a5478ea-6d1a-4227-b420-4d023f430470","filename":"/projects/71d05d9f-884f-4ae9-80d7-2563cc75a382/.sage/temp/compute6dc2/5356/tmp_vI3xYQ.gif"}}︡{"once":false,"file":{"show":true,"uuid":"2a5478ea-6d1a-4227-b420-4d023f430470","filename":"/projects/71d05d9f-884f-4ae9-80d7-2563cc75a382/.sage/temp/compute6dc2/5356/tmp_vI3xYQ.gif"}}︡{"once":false,"file":{"show":true,"uuid":"2a5478ea-6d1a-4227-b420-4d023f430470","filename":"/projects/71d05d9f-884f-4ae9-80d7-2563cc75a382/.sage/temp/compute6dc2/5356/tmp_vI3xYQ.gif"}}︡
︠47d960c7-721b-4c63-a144-d77c28e81967︠












